/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/modelSkateboard1234.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function ModeBoard1234(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/modelSkateboard1234.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="skate_board" geometry={nodes.skate_board.geometry} material={nodes.skate_board.material} position={[0.021, -0.259, -0.006]} scale={0.374} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/modelSkateboard1234.glb')
